### ISSUE TITLE
Suggest renaming repo to something more distinctive

### ISSUE THREAD

**Issue by sowbug** [WebBluetoothCG/demos#10]
My usual pattern for cloning GitHub repos is this:

```
cd ~/Dropbox/src
git clone url-of-repo
```

In the case of this repo, this ends up putting `demos` among a set of distinctively named repositories. Yet `demos` is not distinctive.

How about `web-bluetooth-demos` instead?

**Comment by scheib** [comment]
I could go either way, but I'd bias towards leaving the name.

If I'm certain I'm not sending any pull requests, I just `git clone url name-i-want`
Most of the time I fork first so that I can send pull requests.
I then rename my fork as necessary, e.g.
  https://github.com/scheib/webbluetoothcg-demos
  https://github.com/scheib/beaufortfrancois-sandbox
Then I git clone my fork locally,
then `git repo add upstream <the upstream url>`

**Comment by jyasskin** [comment]
The lack of distinctiveness (in all this CG's repository names) is a pain for anyone forking or cloning the repository. If we eventually move to the w3c organization, they'll need to be prefixed anyway, so maybe we should do it now? I don't have a firm position, but I'm inclined to listen to the newbie over the folks who've already paid the cost. :)

**Comment by jyasskin** [comment]
Bleh. @scheib pointed out that existing links will break, and everyone will need to update their remotes. To fix the links, we'd want to re-create a 'demos' repo after the rename, which points to the new name, with a full gh-pages branch that redirects each .html file to its new name. Then there's a risk that folks will be confused between the 'demos' and 'web-bluetooth-demos' repositories, especially since their un-renamed remotes would continue to find a repository.

I still wouldn't object if @beaufortfrancois wants to do this, but I'm now inclined to leave it alone until/unless we move organizations.

**Comment by sowbug** [comment]
GitHub handles web redirects for you. Yes, git remotes would need to change.

**Comment by jyasskin** [comment]
Oh! If even https://webbluetoothcg.github.io/demos/bluetooth-toy-plane/ would redirect automatically, I'll be happy to rename.

**Comment by sowbug** [comment]
It's easy enough to test. I haven't extensively tested GitHub Pages
redirects, but the repo web links all do the right thing. I have renamed
personal repos many times.

**Comment by jyasskin** [comment]
Sadly, no: https://jyasskin.github.io/testing/ vs https://github.com/jyasskin/testing/blob/gh-pages/index.html

I've filed a bug.
